import type { Policy, MPFAccount, MPFStatement, Document, ProductType, SyncLogEntry, PolicyBenefit, PolicyHistory, Proposal, Activity, Compliance, Customer, Contact, Campaign, Lead, CommissionRecord, RevenueRecord, InvoiceRecord, ComplianceRecord, Company, Individual } from './types';

export const MOCK_LEADS: Lead[] = [
  {
    id: 'L-001',
    type: 'Company',
    leadName: 'Demo Expansion Project',
    companyName: 'ABC Holdings Ltd',
    contactPerson: 'User A',
    contactTitle: 'HR Director',
    email: 'user.a@demo.com',
    phone: '+852 0000-1111',
    source: 'Website',
    campaign: 'Q1 Digital Campaign',
    region: 'HK',
    assignedSales: 'Sales Rep A',
    leadStatus: 'In Progress',
    temperature: 'Warm',
    temperature_score: 65,
    temperature_source: 'auto',
    lastContactDate: '2024-03-25',
    followUpPriority: 'High',
    notesSummary: 'Interested in group medical for 25 new staff.',
    createdDate: '2024-03-20',
    lastUpdated: '2024-03-25',
    industry: 'Technology',
    parentCompany: 'ABC Group International'
  },
  {
    id: 'L-002',
    type: 'Company',
    leadName: 'Demo Startup Benefit Plan',
    companyName: 'XYZ Corporation',
    contactPerson: 'User B',
    contactTitle: 'Founder',
    email: 'user.b@demo.com',
    phone: '+852 1111-2222',
    source: 'Referral',
    campaign: 'Partner Referral',
    region: 'HK',
    assignedSales: 'Sales Rep B',
    leadStatus: 'Converted',
    temperature: 'Hot',
    temperature_score: 92,
    temperature_source: 'auto',
    lastContactDate: '2024-03-28',
    followUpPriority: 'Medium',
    notesSummary: 'Referred by existing client. Needs MPF and Group Medical.',
    createdDate: '2024-03-22',
    lastUpdated: '2024-03-28',
    linkedProposalId: 'P-QUAL-001',
    industry: 'Energy',
    parentCompany: 'XYZ Holdings Group'
  },
  {
    id: 'L-003',
    type: 'Individual',
    leadName: 'Demo Wealth Management',
    companyName: '', // Individual
    contactPerson: 'John Demo',
    contactTitle: 'Senior Vice President',
    email: 'john.demo@example.com',
    phone: '+852 9999-8888',
    source: 'Marketing',
    campaign: 'Wealth Management Seminar',
    region: 'Mainland China',
    country: 'China',
    assignedSales: 'Sales Rep C',
    leadStatus: 'New',
    temperature: 'Warm',
    temperature_score: 72,
    temperature_source: 'auto',
    lastContactDate: '2024-04-10',
    followUpPriority: 'High',
    notesSummary: 'Interested in high-end medical and endowment plans.',
    createdDate: '2024-04-01',
    lastUpdated: '2024-04-10',
    gender: 'Male',
    hkidPassport: 'A000000(0)'
  }
];

export const MOCK_PROPOSALS: Proposal[] = [
  {
    id: 'P-10-001',
    name: 'Demo Office Setup',
    stage: 'Qualification',
    probability: 30,
    expectedRevenueGross: 50000,
    expectedRevenueNet: 45000,
    salesRep: 'Sales Rep A',
    splitRatio: '100%',
    campaign: 'Website Lead Gen',
    source: 'Website',
    businessType: 'NB',
    productCategory: 'Medical',
    productItem: 'Group Medical',
    effectiveDate: '2024-06-01',
    remarks: 'Initial discovery phase.',
    contactPerson: 'User A',
    opportunitySummary: 'Interested in basic medical plan for 10 employees.',
    createdDate: '2024-03-28',
    lastUpdated: '2024-03-28',
    stageLastUpdated: '2024-03-28',
    owner: 'Sales Rep A',
    sourceSystem: 'CRM',
    mcr: 0.75,
    lossRatio: 0.65,
    conversionRate: 0.2,
    estimatedContribution: 15000,
    estimatedCommission: 5000,
    estimatedRevenue: 45000,
    aum: 500000
  },
  {
    id: 'P-QUAL-001',
    name: 'XYZ Corp Startup Plan',
    stage: 'Qualification',
    probability: 30,
    expectedRevenueGross: 120000,
    expectedRevenueNet: 108000,
    salesRep: 'Sales Rep B',
    splitRatio: '100%',
    campaign: 'Referral Program',
    source: 'Referral',
    businessType: 'NB',
    productCategory: 'Medical',
    productItem: 'Group Medical',
    effectiveDate: '2024-07-01',
    remarks: 'Feasibility check ongoing.',
    insurerTentative: 'AIA',
    regionMarket: 'HK',
    proposalType: 'Standard',
    expectedEffectiveDate: '2024-07-01',
    existingProvider: 'None',
    competitiveSituation: 'Direct approach',
    complianceCheckStatus: 'Pending',
    qualificationNotes: 'Company is a new startup, needs flexible options.',
    createdDate: '2024-03-25',
    lastUpdated: '2024-03-29',
    stageLastUpdated: '2024-03-29',
    owner: 'Sales Rep B',
    sourceSystem: 'CRM',
    linkedLeadId: 'L-002',
    mcr: 0.72,
    lossRatio: 0.60,
    conversionRate: 0.35,
    estimatedContribution: 35000,
    estimatedCommission: 12000,
    estimatedRevenue: 108000,
    aum: 1200000
  },
  {
    id: 'P1',
    name: 'Company A Group Medical Plan',
    stage: 'Proposal Preparation',
    probability: 70,
    expectedRevenueGross: 200000,
    expectedRevenueNet: 180000,
    salesRep: 'Sales Rep A',
    splitRatio: '100%',
    campaign: 'Digital Marketing Q1',
    source: 'Website',
    businessType: 'NB',
    productCategory: 'Medical',
    productItem: 'Group Medical',
    effectiveDate: '2024-05-01',
    remarks: 'Preparing final benefit table.',
    client: 'Company A',
    insured: 'Company A Employees',
    insurer: 'AIA',
    currency: 'HKD',
    planType: 'Executive',
    memberCountSummary: '150 Employees',
    pricingBasis: 'Per Head',
    premiumEstimate: 180000,
    proposalPreparationStatus: 'In Progress',
    requiredDocumentsChecklist: ['Business Registration', 'Employee List'],
    internalReviewStatus: 'Pending',
    benefitTable: [
      { id: 'B1', class: 'All', benefit: 'Hospitalization', coverage: 'Full', category: 'Medical' },
      { id: 'B2', class: 'All', benefit: 'Outpatient', coverage: '80%', category: 'Medical' },
    ],
    mcr: 0.85,
    lossRatio: 0.65,
    conversionRate: 0.45,
    estimatedContribution: 15000,
    estimatedCommission: 20000,
    estimatedRevenue: 180000,
    aum: 0,
    createdDate: '2024-03-01',
    lastUpdated: '2024-03-25',
    stageLastUpdated: '2024-03-20',
    owner: 'Sales Rep A',
    sourceSystem: 'CRM'
  },
  {
    id: 'P2',
    name: 'Company B Renewal',
    stage: 'Negotiation',
    probability: 90,
    expectedRevenueGross: 500000,
    expectedRevenueNet: 450000,
    salesRep: 'Sales Rep B',
    splitRatio: '100%',
    campaign: 'Renewal Campaign',
    source: 'Renewal',
    businessType: 'Renewal',
    productCategory: 'Medical',
    productItem: 'Group Medical',
    effectiveDate: '2024-04-01',
    remarks: 'Finalizing discount terms.',
    finalQuotedPremium: 440000,
    discountCommercialAdjustment: '5% Loyalty Discount',
    commissionPercentage: 10,
    negotiationStatus: 'Final Review',
    pendingIssues: 'None',
    clientFeedbackSummary: 'Happy with the terms.',
    internalApprovalStatus: 'Approved',
    finalReviewNote: 'Ready for client signature.',
    benefitTable: [
      { id: 'B3', class: 'All', benefit: 'Hospitalization', coverage: 'Full', category: 'Medical' },
    ],
    mcr: 0.92,
    lossRatio: 0.78,
    conversionRate: 0.85,
    estimatedContribution: 40000,
    estimatedCommission: 50000,
    estimatedRevenue: 450000,
    aum: 0,
    createdDate: '2024-02-15',
    lastUpdated: '2024-03-28',
    stageLastUpdated: '2024-03-25',
    owner: 'Sales Rep B',
    sourceSystem: 'CRM'
  },
  {
    id: 'P-WON-001',
    name: 'DEF Group Life Plan',
    stage: 'Won',
    probability: 100,
    expectedRevenueGross: 300000,
    expectedRevenueNet: 270000,
    salesRep: 'Sales Rep C',
    splitRatio: '100%',
    campaign: 'Direct Outreach',
    source: 'Direct',
    businessType: 'NB',
    productCategory: 'Life',
    productItem: 'Group Life',
    effectiveDate: '2024-02-01',
    remarks: 'Won and policy issued.',
    finalPremium: 250000,
    finalCommission: 25000,
    finalProductPlanConfirmation: 'Group Life Standard',
    finalClientConfirmation: 'Confirmed',
    wonDate: '2024-01-30',
    activationReadyStatus: 'Ready',
    finalRevenue: 270000,
    contractDuration: '12 Months',
    benefitTable: [
      { id: 'B4', class: 'All', benefit: 'Life Coverage', coverage: '36x Salary', category: 'Life' },
    ],
    mcr: 0.95,
    lossRatio: 0.4,
    conversionRate: 1.0,
    estimatedContribution: 25000,
    estimatedCommission: 25000,
    estimatedRevenue: 270000,
    aum: 0,
    createdDate: '2024-01-10',
    lastUpdated: '2024-03-30',
    stageLastUpdated: '2024-01-30',
    owner: 'Sales Rep C',
    sourceSystem: 'CRM',
    linkedPolicyId: 'POL-WON-001'
  },
  {
    id: 'P-LOST-001',
    name: 'GHI Corp Group Medical',
    stage: 'Lost',
    probability: 0,
    expectedRevenueGross: 150000,
    expectedRevenueNet: 135000,
    salesRep: 'Sales Rep A',
    splitRatio: '100%',
    campaign: 'Cold Calling',
    source: 'Cold Call',
    businessType: 'NB',
    productCategory: 'Medical',
    productItem: 'Group Medical',
    effectiveDate: '2024-03-01',
    remarks: 'Lost to competitor.',
    lostReason: 'Price',
    lostDate: '2024-02-28',
    lostNotes: 'Competitor offered 15% lower premium with same coverage.',
    createdDate: '2024-01-15',
    lastUpdated: '2024-02-28',
    stageLastUpdated: '2024-02-28',
    owner: 'Sales Rep A',
    sourceSystem: 'CRM',
    mcr: 0.80,
    lossRatio: 0.70,
    conversionRate: 0.0,
    estimatedContribution: 0,
    estimatedCommission: 0,
    estimatedRevenue: 0,
    aum: 0
  },
  {
    id: 'P-REN-001',
    name: 'Company B Renewal 2024',
    stage: 'Proposal Preparation',
    probability: 70,
    expectedRevenueGross: 550000,
    expectedRevenueNet: 495000,
    salesRep: 'Sales Rep B',
    splitRatio: '100%',
    campaign: 'Renewal Campaign',
    source: 'Renewal',
    businessType: 'Renewal',
    productCategory: 'Medical',
    productItem: 'Group Medical',
    effectiveDate: '2024-06-01',
    remarks: 'Renewal for POL-DEMO-002',
    linkedPreviousPolicyId: 'POL-DEMO-002',
    createdDate: '2024-03-01',
    lastUpdated: '2024-03-30',
    stageLastUpdated: '2024-03-25',
    owner: 'Sales Rep B',
    sourceSystem: 'CRM',
    mcr: 0.90,
    lossRatio: 0.75,
    conversionRate: 0.80,
    estimatedContribution: 50000,
    estimatedCommission: 55000,
    estimatedRevenue: 495000,
    aum: 0
  }
];

export const MOCK_ACTIVITIES: Activity[] = [
  { id: 'A1', type: 'Meeting', relatedObject: 'P1', relatedObjectType: 'Proposal', owner: 'Sales Rep A', date: '2024-03-20', subject: 'Benefit Review' },
  { id: 'A2', type: 'Call', relatedObject: 'P-LEAD-001', relatedObjectType: 'Proposal', owner: 'Sales Rep B', date: '2024-03-22', subject: 'Initial Discovery' },
];

export const MOCK_COMPLIANCE_RECORDS: ComplianceRecord[] = [
  {
    id: 'CR-001',
    individualId: 'IND-001',
    status: 'Approved',
    kycStatus: 'Verified',
    amlStatus: 'Clear',
    riskLevel: 'Low',
    lastCheckedDate: '2024-03-15',
    expiryDate: '2025-03-15',
    checkedBy: 'Compliance Officer 01',
    reviewNotes: 'All background checks passed. Identity documents verified.',
    linkedDocumentsCount: 3
  },
  {
    id: 'CR-002',
    individualId: 'IND-002',
    status: 'Pending',
    kycStatus: 'In Progress',
    amlStatus: 'Pending',
    riskLevel: 'Medium',
    lastCheckedDate: '2024-04-01',
    expiryDate: '2025-04-01',
    checkedBy: 'Compliance Officer 02',
    reviewNotes: 'Waiting for additional bank statement for AML verification.',
    linkedDocumentsCount: 1
  }
];

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'COMP-001',
    name: 'SAMPLE HOLDINGS LTD',
    chineseName: '示範控股有限公司',
    type: 'Limited Company',
    registrationNo: '00000001',
    industry: 'Aviation',
    region: 'HK',
    country: 'Hong Kong',
    assignedSales: 'Sales Rep A',
    team: 'Sales Team A',
    status: 'Active',
    createdDate: '2020-01-01',
    lastUpdated: '2024-03-20'
  },
  {
    id: 'COMP-002',
    name: 'DEMO UTILITIES LTD',
    chineseName: '示範公用事業有限公司',
    type: 'Utility',
    registrationNo: '00000002',
    industry: 'Energy',
    region: 'HK',
    country: 'Hong Kong',
    assignedSales: 'Sales Rep B',
    team: 'Sales Team B',
    status: 'Active',
    createdDate: '2020-01-01',
    lastUpdated: '2024-03-25'
  }
];

export const MOCK_INDIVIDUALS: Individual[] = [
  {
    id: 'IND-001',
    fullName: 'Ms. Jane Test',
    chineseName: '示範姓名',
    gender: 'Female',
    dateOfBirth: '1985-01-01',
    hkidPassport: 'A000000(0)',
    jobTitle: 'Office Manager',
    department: 'Administration',
    email: 'jane.test@demo.com',
    directLine: '+852 0000-0000',
    mobile: '+852 9999-8888',
    address: '1/F Demo Building, 1 Sample Street, Hong Kong',
    region: 'HK',
    country: 'Hong Kong',
    linkedCompanyId: 'COMP-001',
    roleType: 'Primary Contact',
    status: 'Active',
    createdDate: '2021-06-15',
    lastUpdated: '2024-03-20'
  },
  {
    id: 'IND-002',
    fullName: 'John Demo',
    chineseName: '示範人士',
    gender: 'Male',
    dateOfBirth: '1978-01-01',
    hkidPassport: 'B111111(1)',
    jobTitle: 'Senior Vice President',
    department: 'Investment',
    email: 'john.demo@example.com',
    directLine: '',
    mobile: '+852 9999-7777',
    address: '1/F Demo Building, 1 Sample Street, Hong Kong',
    region: 'Mainland China',
    country: 'China',
    roleType: 'VIP Client',
    status: 'Active',
    createdDate: '2024-04-01',
    lastUpdated: '2024-04-10'
  }
];

export const MOCK_CONTACTS: Contact[] = [
  { id: 'CON1', fullName: 'Ms. Jane Test', company: 'SAMPLE VENTURES GROUP', jobTitle: 'Office Manager', phone: '+852 0000-1111', directLine: '+852 0000-0000', mobile: '+852 9999-8888', email: 'jane.test@demo.com', validity: 'Valid', type: 'Primary' },
  { id: 'CON2', fullName: 'Mr. Alex Sample', company: 'SAMPLE VENTURES GROUP', jobTitle: 'Benefits Coordinator', phone: '+852 1111-2222', directLine: '+852 1111-0000', mobile: '+852 9999-7777', email: 'alex.sample@demo.com', validity: 'Valid', type: 'Secondary' },
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  { id: 'CP1', name: 'Client Referral', eventDate: '-', mode: '-', category: '-', responsible: '-', contacts: 0, registered: 0, attended: 0, oppty: 4, activities: 6, active: true },
  { id: 'CP2', name: 'Cold Calling', eventDate: '-', mode: '-', category: '-', responsible: '-', contacts: 0, registered: 0, attended: 0, oppty: 2, activities: 2, active: true },
];

export const MOCK_REFERRERS = [
  { id: 'R1', name: 'Sample Partners Ltd', type: 'Corporate', contact: 'Agent 01', status: 'Active' },
  { id: 'R2', name: 'Independent Agent - Demo', type: 'Individual', contact: 'Agent 02', status: 'Active' },
];

export const MOCK_INSURERS = [
  { id: 'I1', name: 'AIA', rating: 'A+', country: 'HK', status: 'Approved' },
  { id: 'I2', name: 'Bupa', rating: 'A', country: 'UK', status: 'Approved' },
  { id: 'I3', name: 'AXA', rating: 'A+', country: 'FR', status: 'Approved' },
];

export const MOCK_MAILINGS = [
  { id: 'M1', name: 'Q1 Newsletter', date: '2024-01-15', status: 'Sent', recipients: 1200 },
  { id: 'M2', name: 'Group Medical Promo', date: '2024-02-20', status: 'Sent', recipients: 450 },
];

export const MOCK_MAILING_LISTS = [
  { id: 'ML1', name: 'All Corporate Clients', count: 850, type: 'Dynamic' },
  { id: 'ML2', name: 'Prospects - HK Region', count: 320, type: 'Static' },
];

export const MOCK_POLICIES: Policy[] = [
  {
    id: '1',
    policyNo: 'POL-DEMO-001',
    customer: 'User C',
    provider: 'Prudential',
    effectiveDate: '2023-01-01',
    expiryDate: '2023-12-31',
    premiumTotal: 15000,
    annualizedPremium: 15000,
    status: 'Active',
    renewRequired: false,
    crmProposalId: 'CRM-PROP-001',
    crmProposalStatus: 'Finalized',
    productType: 'Insurance-Individual',
    currency: 'HKD',
    billingMethod: 'Direct Debit',
    debitNoteNo: 'DN-DEMO-001',
    remarks: 'Standard individual policy',
    customerCode: 'CUST-001',
    industry: 'Technology',
    providerCode: 'PRU-001',
    productPlanRef: 'PRU-LIFE-001',
    salesOwner: 'Sales Rep A',
    salesTeam: 'Team A',
    referrerProducer: 'Direct',
    premiumFrequency: 'Annual',
    premiumType: 'Standard',
    grossPremium: 15000,
    netPremium: 14500,
    commissionRate: 5,
    clientDiscountAmount: 500,
    lastUpdated: '2024-03-20 10:00',
    documentCount: 3,
  },
  {
    id: '2',
    policyNo: 'POL-DEMO-002',
    customer: 'User D',
    provider: 'AXA',
    effectiveDate: '2023-06-01',
    expiryDate: '2024-05-31',
    premiumTotal: 8000,
    annualizedPremium: 8000,
    status: 'Renewal Due',
    renewRequired: true,
    crmProposalId: 'P-REN-001',
    crmProposalStatus: 'Proposal Preparation',
    sourceProposalId: 'P-OLD-001',
    productType: 'Insurance-Group-EBP',
    currency: 'HKD',
    billingMethod: 'Cheque',
    debitNoteNo: 'DN-DEMO-002',
    remarks: 'Group health insurance',
    customerCode: 'CUST-002',
    industry: 'Finance',
    providerCode: 'AXA-001',
    productPlanRef: 'AXA-HEALTH-001',
    salesOwner: 'Sales Rep B',
    salesTeam: 'Team B',
    referrerProducer: 'Referral Agent',
    premiumFrequency: 'Monthly',
    premiumType: 'Group',
    grossPremium: 8000,
    netPremium: 7800,
    commissionRate: 3,
    clientDiscountAmount: 200,
    lastUpdated: '2024-03-25 14:30',
    documentCount: 5,
  },
  {
    id: '3',
    policyNo: 'POL-DEMO-003',
    customer: 'User E',
    provider: 'Manulife',
    effectiveDate: '2022-01-01',
    expiryDate: '2022-12-31',
    premiumTotal: 5000,
    annualizedPremium: 5000,
    status: 'Lapsed',
    renewRequired: false,
    crmProposalId: 'CRM-PROP-003',
    crmProposalStatus: 'Finalized',
    productType: 'Insurance-Individual',
    currency: 'USD',
    billingMethod: 'Credit Card',
    debitNoteNo: 'DN-DEMO-003',
    lostLapsedReason: 'Price too high',
    remarks: 'Policy lapsed after non-payment',
    customerCode: 'CUST-003',
    industry: 'Education',
    providerCode: 'MAN-001',
    productPlanRef: 'MAN-LIFE-001',
    salesOwner: 'Sales Rep C',
    salesTeam: 'Team C',
    referrerProducer: 'Broker Partner',
    premiumFrequency: 'Quarterly',
    premiumType: 'Standard',
    grossPremium: 5000,
    netPremium: 4900,
    commissionRate: 2,
    clientDiscountAmount: 100,
    lastUpdated: '2023-01-15 09:00',
    documentCount: 2,
  },
];

export const MOCK_POLICY_BENEFITS: PolicyBenefit[] = [
  {
    id: '1',
    planName: 'Standard Health',
    employeeClass: 'Class A',
    benefit: 'Hospitalization',
    coverage: 'Full Coverage',
    coverageCategory: 'Medical',
    valueLimit: '1,000,000',
    headcountEmployee: 50,
    headcountSpouse: 20,
    headcountChildren: 30,
    headcountOther: 0,
  },
  {
    id: '2',
    planName: 'Standard Health',
    employeeClass: 'Class B',
    benefit: 'Outpatient',
    coverage: '80% Reimbursement',
    coverageCategory: 'Medical',
    valueLimit: '50,000',
    headcountEmployee: 100,
    headcountSpouse: 40,
    headcountChildren: 60,
    headcountOther: 5,
  },
];

export const MOCK_POLICY_HISTORY: PolicyHistory[] = [
  {
    id: '1',
    timestamp: '2023-01-01 09:00',
    eventType: 'Policy Draft Created',
    performedBy: 'System',
    remark: 'Initial sync from CRM',
  },
  {
    id: '2',
    timestamp: '2023-01-01 10:00',
    eventType: 'Activated',
    performedBy: 'Admin',
    remark: 'Policy activated after payment confirmation',
  },
  {
    id: '3',
    timestamp: '2024-03-20 10:00',
    eventType: 'Document Uploaded',
    performedBy: 'System Admin',
    remark: 'Signed policy document uploaded',
  },
];

export const MOCK_MPF_ACCOUNTS: MPFAccount[] = [
  {
    id: '1',
    accountId: 'MPF-SAMPLE-001',
    customer: 'Sample Corp Ltd',
    provider: 'HSBC',
    scheme: 'SuperTrust Plus',
    clientCode: 'C00001',
    latestAUM: 1500000,
    lastStatementTotal: 1450000,
    currency: 'HKD',
    status: 'Active',
    company: 'GMAC',
    crmProposalId: 'CRM-PROP-004',
  },
];

export const MOCK_STATEMENTS: MPFStatement[] = [
  {
    id: '1',
    statementId: 'STMT-001',
    company: 'GMAC',
    provider: 'HSBC',
    commissionDate: '2024-02-15',
    statementDate: '2024-02-01',
    totalAmount: 45000,
    remark: 'Monthly commission',
    status: 'Completed',
  },
];

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: '1',
    fileName: 'sample_document.pdf',
    category: 'Proposal',
    linkedObject: 'CRM-PROP-001',
    linkedObjectType: 'Proposal (CRM)',
    uploadedBy: 'Admin',
    uploadDate: '2024-03-20',
    version: '1.0',
  },
];

export const MOCK_SYNC_LOGS: SyncLogEntry[] = [
  {
    id: '1',
    timestamp: '2024-03-30 10:00:00',
    objectType: 'Proposal',
    action: 'Sync',
    status: 'Success',
    sourceSystem: 'CRM',
    targetSystem: 'GMI'
  },
  {
    id: '2',
    timestamp: '2024-03-30 10:05:00',
    objectType: 'Policy',
    action: 'Create',
    status: 'Success',
    sourceSystem: 'GMI',
    targetSystem: 'DB'
  },
  {
    id: '3',
    timestamp: '2024-03-30 10:10:00',
    objectType: 'System',
    action: 'Backup',
    status: 'Warning',
    errorMessage: 'Backup partially completed',
    sourceSystem: 'Server',
    targetSystem: 'Cloud'
  },
  {
    id: '4',
    timestamp: '2024-03-30 10:15:00',
    objectType: 'Lead',
    action: 'Sync',
    status: 'Error',
    errorMessage: 'Field mapping error: temperature_score',
    sourceSystem: 'External API',
    targetSystem: 'CRM'
  }
];

export const MOCK_COMMISSIONS: CommissionRecord[] = [
  {
    id: 'COM-001',
    sourcePolicyId: '1',
    sourceProposalId: 'P-WON-001',
    client: 'DEF Group',
    insurer: 'AIA',
    product: 'Group Life',
    businessType: 'NB',
    premium: 250000,
    commissionRate: 10,
    commissionAmount: 25000,
    paymentType: 'Upfront',
    paymentFrequency: 'Yearly',
    status: 'Received',
    currency: 'HKD',
    createdDate: '2024-01-30'
  },
  {
    id: 'COM-002',
    sourcePolicyId: '2',
    sourceProposalId: 'P-REN-001',
    client: 'Company B',
    insurer: 'AXA',
    product: 'Group Medical',
    businessType: 'Renewal',
    premium: 8000,
    commissionRate: 3,
    commissionAmount: 240,
    paymentType: 'Recurring',
    paymentFrequency: 'Monthly',
    status: 'Pending',
    currency: 'HKD',
    createdDate: '2024-03-25'
  }
];

export const MOCK_REVENUES: RevenueRecord[] = [
  {
    id: 'REV-001',
    sourcePolicyId: '1',
    revenueType: 'Premium Revenue',
    totalAmount: 250000,
    recognizedAmount: 125000,
    remainingAmount: 125000,
    recognitionMethod: 'Monthly',
    recognitionStartDate: '2024-02-01',
    recognitionEndDate: '2025-01-31',
    status: 'Partially Recognized',
    currency: 'HKD'
  },
  {
    id: 'REV-002',
    sourcePolicyId: '1',
    revenueType: 'Commission Revenue',
    totalAmount: 25000,
    recognizedAmount: 25000,
    remainingAmount: 0,
    recognitionMethod: 'Upfront',
    recognitionStartDate: '2024-01-30',
    recognitionEndDate: '2024-01-30',
    status: 'Recognized',
    currency: 'HKD'
  }
];

export const MOCK_INVOICES: InvoiceRecord[] = [
  {
    id: 'INV-2024-001',
    sourceProposalId: 'P-WON-001',
    sourcePolicyId: '1',
    client: 'DEF Group',
    invoiceAmount: 250000,
    currency: 'HKD',
    issueDate: '2024-01-15',
    dueDate: '2024-02-15',
    status: 'Paid'
  },
  {
    id: 'INV-2024-002',
    sourceProposalId: 'P-REN-001',
    sourcePolicyId: '2',
    client: 'Company B',
    invoiceAmount: 8000,
    currency: 'HKD',
    issueDate: '2024-03-25',
    dueDate: '2024-04-25',
    status: 'Issued'
  }
];

export const CONFIG_CURRENCIES = ['HKD', 'USD', 'CNY', 'EUR'];
export const CONFIG_PRODUCT_TYPES: ProductType[] = ['Insurance-Individual', 'Insurance-Group-EBP', 'MPF'];
export const CRM_CUSTOMERS = ['User D', 'User C', 'Company A', 'Company B', 'Sample Corp Ltd'];
export const CRM_PROVIDERS = ['AIA', 'Bupa', 'Manulife', 'Prudential', 'AXA', 'HSBC'];
export const CONFIG_COMPANIES = ['GMAC', 'GMI', 'GMS'];
export const CONFIG_SCHEMES = ['SuperTrust Plus', 'Global Choice', 'Smart Retirement'];
export const CONFIG_COMMISSION_TYPES = ['1st Year', 'Renewal', 'Trailer', 'Transfer-in'];
